name: Testing
on:
  push:
    branches:
    - master
jobs:
  test:
    name: Testing Swift Package and iOS app
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Force XCode 13.2
        run: sudo xcode-select -switch /Applications/Xcode_13.2.app
      - name: Run Super-Linter
        uses: github/super-linter@v4
